-- FarmPi operational baseline intentionally contains no locations, nodes or readings.
--
-- The earlier 16-paddock synthetic dataset is retained in the dedicated
-- firmware/esp32-sensor test tool and repository history. It must not be
-- silently loaded into a clean operational database.
--
-- Register physical ESP32-S3 nodes through /api/nodes, create farmer-named
-- locations through the Nodes administration flow, and use per-measurement
-- OFF / SIMULATED / LIVE modes for controlled development data.
